export const INPUT_CHANGE_ACTION = "INPUT_CHANGE_ACTION";
export const DEMO_ACTION = "DEMO_ACTION";
export const EMAIL_CHANGE = "EMAIL_CHANGE";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const SHOW_REDUX_DATA = "SHOW_REDUX_DATA";